<a href="https://colab.research.google.com/github/Daria-Lytvynenko/ML_course/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
import numpy as np

In [32]:
vector=np.random.rand(10,)
matrix=np.array([[11,14,17],[20,23,26], [29,32,35]])
vector, vector.shape, matrix, matrix.shape

(array([8.07577048e-01, 9.43291547e-01, 9.45597121e-01, 1.74466308e-01,
        7.94786686e-01, 4.16923459e-04, 6.48721347e-01, 3.71297318e-01,
        6.19671029e-01, 8.41381818e-01]),
 (10,),
 array([[11, 14, 17],
        [20, 23, 26],
        [29, 32, 35]]),
 (3, 3))


### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [20]:
vector_upd=np.round(vector+10, 2)
vector_upd

array([10.25, 10.59, 10.17, 10.45, 10.07, 10.68, 10.23, 10.56, 10.04,
       10.08])

In [21]:
matrix_upd=matrix*2
matrix_upd

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [22]:
vector_sq=np.square(vector_upd)
vector_sq

array([105.0625, 112.1481, 103.4289, 109.2025, 101.4049, 114.0624,
       104.6529, 111.5136, 100.8016, 101.6064])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [23]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [26]:
result_matrix=np.dot(A.T,B.T)
result_matrix

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [28]:
a_c=np.dot(result_matrix, C)
a_c

array([[0.2034],
       [0.2846]])

In [29]:
a_d=np.dot(result_matrix, D)
a_d

array([[0.2034, 0.7281],
       [0.2846, 0.5202]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [30]:
result_matrix.T

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

In [33]:
vector.T, vector.shape

(array([8.07577048e-01, 9.43291547e-01, 9.45597121e-01, 1.74466308e-01,
        7.94786686e-01, 4.16923459e-04, 6.48721347e-01, 3.71297318e-01,
        6.19671029e-01, 8.41381818e-01]),
 (10,))

In [34]:
column_vector=np.expand_dims(vector, axis=1)
column_vector

array([[8.07577048e-01],
       [9.43291547e-01],
       [9.45597121e-01],
       [1.74466308e-01],
       [7.94786686e-01],
       [4.16923459e-04],
       [6.48721347e-01],
       [3.71297318e-01],
       [6.19671029e-01],
       [8.41381818e-01]])

In [35]:
column_vector.T, column_vector.T.shape

(array([[8.07577048e-01, 9.43291547e-01, 9.45597121e-01, 1.74466308e-01,
         7.94786686e-01, 4.16923459e-04, 6.48721347e-01, 3.71297318e-01,
         6.19671029e-01, 8.41381818e-01]]),
 (1, 10))